version: '3.4'

services:
  django:
    image: django
    container_name: django
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: server
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  pgadmin4:
    image: elestio/pgadmin:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: adan@sevilla.es
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "8080:8080"